### ISSUE TITLE
BTW, updated these docs

### ISSUE THREAD

**Issue by williamFalcon** [sebamenabar/MyPytorchLighthningBoilerplate#1]
https://pytorch-lightning.readthedocs.io/en/0.7.4/hyperparameters.html#argparser-best-practices

**Comment by sebamenabar** [comment]
Thanks, I think using `trainer = Trainer.from_argparse_args(hparams, early_stopping_callback=...)` is definitely better and changed that.

Regarding other ugly stuff I make; I manually add the pl Trainer args instead of using `Trainer.add_argparse_args` because  it would override the `argparse.ArgumentDefaultsHelpFormatter`(I want to the see the default values of my arguments). 

I manually modify the gpus parameter because I prefer to see it on top when running with the `--help` flag and with a description on how to use it.

The epochs override is only based on how I structure my config file (I have it as cfg.train.epochs).

I ended up copying what is done in https://github.com/PyTorchLightning/pytorch-lightning/blob/761252be78ba573ad1f5c700190eb89b13e41e99/pytorch_lightning/trainer/trainer.py#L589
and adding more elements to the blacklist to achieve what I want, so the solution would be to simple have and additional argument in Trainer.add_argparse_args to add more elements to the blacklist and some way (don't know how really) to avoid overriding the args formatter.

It probably would have been better if a submited an issue with this to the pl repo, but I just wanted to do something quick for myself.
If you have any remarks on further best practices I'd love to hear them! Thanks!
